//ADIÇÃO
var adiçao = 1 + 2;
console.log(adiçao)

//subtração 

var subtração = 3 - 1;
console.log(subtração);

//multiplicação 

var multiplicação = 2 * 4;
console.log(multiplicação)

//divisão real 

var divisãoReal = 6 / 2;
console.log(divisãoReal);

//divisão inteira

var divisaoInteira = 5 % 2;
console.log(divisaoInteira);

//potenciação

var potenciação = 2 ** 10;
console.log(potenciação);

// maior que 

var maiorQue = 3 > 2;
console.log(maiorQue);

//menor

var menorQue = 1 < 3;
console.log(menorQue);

// maior ou igual a 

var maiorOuIgual = 5 >= 2;
console.log(maiorOuIgual);

//manor ou igual a 

var menorOuIgual = 5 <= 8;
console.log(menorOuIgual);

